import { Quicksand } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Topbar from "@/components/shared/Topbar";
import Footer from "@/components/shared/Footer";
import { CartProvider } from "@/context/CartContext";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata = {
  title: "Favrio Clothing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={quicksand.className}>
        <div className="max-w-screen-2xl mx-auto">
          <CartProvider>

          <div className="mb-20 lg:mb-36">
          <Navbar></Navbar>
          <Topbar></Topbar>
          </div>

          {children}
          <Footer></Footer>
          </CartProvider>
        </div>
      </body>
    </html>
  );
}
